### ISSUE TITLE
Json-API: counts should be integers

### ISSUE THREAD

**Issue by ku-antum** [QISKit/qiskit-api-py#32]
Example snippet from a job-result json document:
`"... counts":{"0000000000000100":0.9999999999999999,"0000000000001001":1.9999999999999998,...`

This should rather look like
`"... counts":{"0000000000000100":1,"0000000000001001":2, ...`.

What's the reason for supplying counts not as integers?

**Comment by pacomf** [comment]
Fixed in Quantum Experience API, with new version 3.10.0: https://quantumexperience.ng.bluemix.net/api/version

:)

**Comment by ku-antum** [comment]
Thanks!  The work on the API is very much appreciated.
