### ISSUE TITLE
_quantumprogram.py syntax error in Python 3.4 due to dictionary merging

### ISSUE THREAD

**Issue by dan9thsense** [QISKit/qiskit-api-py#39]
_quantumprogram.py generates a syntax error with Python 3.4 due to dictionary merging that is not supported in python 3.4. See this topic: 
https://stackoverflow.com/questions/38987/how-to-merge-two-dictionaries-in-a-single-expression

Here is the error message:

File "../../qiskit-sdk-py/qiskit/_quantumprogram.py", line 1002
    "config": {**job["config"], **qobj["config"]}})
                ^
SyntaxError: invalid syntax

**Comment by dtmcclure** [comment]
Based on the stackoverflow discussion referenced above, it seems like the for loop at that point in _quantumprogram should be replaced with the version below in order to make this code work for any version of Python 3.

             for job in qobj["circuits"]:
                fullconfig = job["config"].copy()
                fullconfig.update(qobj["config"])
                jobs.append({"compiled_circuit": job["compiled_circuit"],
                             "config": fullconfig})

**Comment by pacomf** [comment]
This issue is related to SDK no API :), so i close the issue.
@dan9thsense, @dtmcclure , you can open in the SDK repository: https://github.com/QISKit/qiskit-sdk-py/issues

Thank you!

**Comment by dan9thsense** [comment]
Opened a new issue there.
