### ISSUE TITLE
get_jobs result is not ordered

### ISSUE THREAD

**Issue by ajavadia** [QISKit/qiskit-api-py#59]
The `get_jobs()` method has a `limit` argument, and it will return that many results from the jobs the user has previously executed. However, n jobs seem to be selected at random, which is not very useful.

Is it possible to modify this so that it returns the **latest** n jobs?
https://github.com/QISKit/qiskit-api-py/blob/c0fef9b8719c7e7824d54041297def5352d075df/IBMQuantumExperience/IBMQuantumExperience.py#L744

**Comment by pacomf** [comment]
This is an issue for QX API... the qiskit-api-py repo is a wrapper of the QX API.

**Comment by francabrera** [comment]
I think this would fix the issue (@pacomf):
```Python
jobs = self.req.get('/Jobs', '&filter={"order": "creationDate DESC", "limit":' + str(limit) + '}')
```
