### ISSUE TITLE
Remove logging configuration

### ISSUE THREAD

**Issue by RonSadlier** [QISKit/qiskit-api-py#63]
The API should not configure how log messages are handled with the logging module, that should be done by the application utilizing the API. I propose the removal of the statement `logging.basicConfig()` in IBMQuantumExperience.py. Currently the inclusion of this statement creates more work for those using the logging module in their own code. If `logging.getLogger()` were used instead it would improve the ability to route log messages emanating from the module.

**Comment by diego-plan9** [comment]
It is a good point, @RonSadlier - would you be interested in submitting a PR yourself to take care of the issue? The basis for using a custom logger is [mostly in place](https://github.com/QISKit/qiskit-api-py/blob/master/IBMQuantumExperience/IBMQuantumExperience.py#L263) - it would mostly be a matter of replicating the the default formatter and handler provided by  `logging.basicConfig()` for that `self.log` instance.

**Comment by RonSadlier** [comment]
Sure thing, @diego-plan9.

I'm wondering if it would be better to move the self.log instance to the module level. The [current statement](https://github.com/QISKit/qiskit-api-py/blob/master/IBMQuantumExperience/IBMQuantumExperience.py#L263) creates a logger with the module name already, so this the change shouldn't affect how users interact with it. A quick test of this at https://github.com/QISKit/qiskit-api-py/commit/fa39e7a8c1d883f984fe70fcc8caefb6ede45d5c doesn't seem to create any problems.

**Comment by diego-plan9** [comment]
Thanks @RonSadlier ! Yes - taking the chance to move to a module-level logger instance with the same name sounds good :+1:
